---
title: "Instacart Dashboard"
author: "Heather Lu"
date: "2025-10-29"
output:
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(tidyverse)
library(plotly)
library(p8105.datasets)
library(flexdashboard)

# Load data & sample 
data("instacart")
set.seed(1)

insta <- instacart |>
  sample_n(min(50000, nrow(instacart))) |>
  mutate(
    dow = factor(order_dow, levels = 0:6,
                 labels = c("Sun","Mon","Tue","Wed","Thu","Fri","Sat"))
  )

# Top categories
top_depts <- insta |>
  count(department, sort = TRUE) |>
  slice_head(n = 8) |>
  pull(department)

top_aisles <- insta |>
  count(aisle, sort = TRUE) |>
  slice_head(n = 10) |>
  pull(aisle)
```

Orders by Day of Week (Bar) {data-height=360}
-----------------------------------------------------------------------

```{r}
insta |>
count(dow) |>
plot_ly(x = ~dow, y = ~n, type = "bar")|>
layout(xaxis = list(title = "Day of week"),
yaxis = list(title = "Number of orders"))
```

Orders by hour of day (Line plot) {data-height=420}
-----------------------------------------------------------------------
```{r}
insta |>
  count(order_hour_of_day, name = "orders") |>
  plot_ly(x = ~order_hour_of_day, y = ~orders,
          type = "scatter", mode = "lines+markers") |>
  layout(title = "Instacart Activity by Hour",
         xaxis = list(title = "Hour of day (0–23)",
                      tickvals = c(0,6,12,18,23)),
         yaxis = list(title = "Number of order lines"))
```

Days since prior order (histogram) {data-height=420}
-----------------------------------------------------------------------
```{r}
insta |>
  filter(!is.na(days_since_prior_order)) |>
  plot_ly(
    x = ~days_since_prior_order,
    type = "histogram", nbinsx = 30
  ) |>
  layout(
    title = "Distribution of Days Since Prior Order",
    xaxis = list(title = "Days since prior order"),
    yaxis = list(title = "Count of line items")
  )
```


